apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabolismo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: metabolismo-app
  template:
    metadata:
      labels:
        app: metabolismo-app
    spec:
      containers:
      - name: metabolismo-app
        image: fernandohs99/metabolismo-app:20
        ports:
        - containerPort: 5010
---
apiVersion: v1
kind: Service
metadata:
  name: metabolismo-service
spec:
  type: NodePort
  selector:
    app: metabolismo-app
  ports:
  - protocol: TCP
    port: 5010
    targetPort: 5010
    nodePort: 30000  # Escolha uma porta disponível no seu cluster para o NodePort
