name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set image tag
      id: set_tag
      run: echo "::set-output name=TAG::v1-${{ github.run_number }}"

    - name: Build Docker image
      run: |
        docker build -t fernandohs99/metabolismo-app:${{ steps.set_tag.outputs.TAG }} .

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push fernandohs99/metabolismo-app:${{ steps.set_tag.outputs.TAG }}

  deploy_to_kubernetes:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
